# Header
menu:
  Home: /
  Archives: /archives
  Courses: /categories/whut
  Whut: /tags/whut
  Playlist: /playlist
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: right
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- archive
- category
- tag
- tagcloud
- links

# Links
links:
	Github: https://github.com/Leouas/



# Miscellaneous
google_analytics:
favicon: /favicon.jpg
twitter: 
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
#duoshuo_shortname: reqianduan

# Baidu share
#baidushare: true
